// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ye5vscFm1eiOiPVBIQ8np-CnGNk4DQc',
    appId: '1:997141921548:web:09ad4be66b79bed6e8d329',
    messagingSenderId: '997141921548',
    projectId: 'student-housing-db',
    authDomain: 'student-housing-db.firebaseapp.com',
    storageBucket: 'student-housing-db.appspot.com',
    measurementId: 'G-8KXXJEN96D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_wnLFbkEfoqY-1cv8R0zoEvS67wF8U6o',
    appId: '1:997141921548:android:658af55b173d84a5e8d329',
    messagingSenderId: '997141921548',
    projectId: 'student-housing-db',
    storageBucket: 'student-housing-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvM14Zr4CQnHG3n593Ldc_Zi_yLYgK6oo',
    appId: '1:997141921548:ios:2b847e89002d59c8e8d329',
    messagingSenderId: '997141921548',
    projectId: 'student-housing-db',
    storageBucket: 'student-housing-db.appspot.com',
    androidClientId:
        '997141921548-mbjgdnj04097h26ecbt5sm054vsrt9d7.apps.googleusercontent.com',
    iosClientId:
        '997141921548-vd0npukhr88vd2dalvm4rd43ft8o3bch.apps.googleusercontent.com',
    iosBundleId: 'com.arisenlab.flutterFinalsWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvM14Zr4CQnHG3n593Ldc_Zi_yLYgK6oo',
    appId: '1:997141921548:ios:2b847e89002d59c8e8d329',
    messagingSenderId: '997141921548',
    projectId: 'student-housing-db',
    storageBucket: 'student-housing-db.appspot.com',
    androidClientId:
        '997141921548-mbjgdnj04097h26ecbt5sm054vsrt9d7.apps.googleusercontent.com',
    iosClientId:
        '997141921548-vd0npukhr88vd2dalvm4rd43ft8o3bch.apps.googleusercontent.com',
    iosBundleId: 'com.arisenlab.flutterFinalsWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ye5vscFm1eiOiPVBIQ8np-CnGNk4DQc',
    appId: '1:997141921548:web:22c842fb2895b3cce8d329',
    messagingSenderId: '997141921548',
    projectId: 'student-housing-db',
    authDomain: 'student-housing-db.firebaseapp.com',
    storageBucket: 'student-housing-db.appspot.com',
    measurementId: 'G-VMMLBSWQYM',
  );
}
